# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: nougat_homepage
email: akurosia@akurosia.de
description: > # this means to ignore newlines until "baseurl:"
  A page for Mister_Nougat_TTV
encoding: utf-8
repository: nougatcrew/nougat_homepage
imageurl: "https://ffxiv.akurosia.de/extras/images/ui/icon"
github_username:  nougatcrew
baseurl: "/nougat_homepage"


# Build settings
#markdown: kramdown
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-commonmark
  - jekyll-include-cache
gem:
  - jekyll-roman
include:
  - _pages
permalink: /:categories/:slug.html
exclude:
  - .git
  - .sass-cache
  - .jekyll-cache
  - _site
  - tmp
  - node_modules
  - assets/node_modules
  - Gemfile
  - Gemfile.lock
  - vendor
  - forestry
  - guide_ffxiv.xlsx
  - ~$guide_ffxiv.xlsx
  - "convert_skills_to_guide_form.py"
  - "ffxiv_guide_xlsx_to_file.py"
  - "generateLinks.py"

sass:
    sass_dir: _sass
    load_paths:
        - _sass
    style: compressed
