backend:
  name: github
  repo: Nougatcrew/nougat_homepage
  branch: jekyll
  base_url: https://us-central1-thinking-window-255219.cloudfunctions.net
  auth_endpoint: /ffxiv-pg-oauth/auth
  open_authoring: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: "assets/img"
locale: 'de'

field_image: &field_image
  label: "Images"
  name: "image"
  widget: "list"
  fields:
    - {label: "urlSmall", name: "urlSmall", required: false, allowMultiple: false, widget: "string"}
    - {label: "url", name: "url", required: false, allowMultiple: false, widget: "string"}
    - {label: "height", name: "height", required: false, allowMultiple: false, widget: "string"}

guide-fields: &guide-fields
  - {label: "Title", name: "title", widget: "string"}
  - {label: "page_type", name: "page_type", widget: "string"}
  - {label: "Date", name: "date", widget: "date"}
  - *field_image
  - {label: "terms", name: "terms", widget: "list", fields: [{label: "term", name: "term", required: false, widget: "string"}]}
  # Hidden fields
  - {label: "CMS Used", name: "cms", widget: "hidden", default: "netlify-cms"}


collections:
  - name: "Events Posts"
    label: "Events Posts"
    delete: false
    label_singular: "Guide"
    folder: "_posts/events/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
  - name: "Team Posts"
    label: "Team Posts"
    delete: false
    label_singular: "Guide"
    folder: "_posts/team/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
  - name: "Partner Posts"
    label: "Partner Posts"
    delete: false
    label_singular: "Guide"
    folder: "_posts/partner/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
