backend:
  name: github
  repo: Nougatcrew/nougat_homepage
  branch: new_posts
  base_url: https://us-central1-thinking-window-255219.cloudfunctions.net
  auth_endpoint: /ffxiv-pg-oauth/auth
  open_authoring: true

publish_mode: editorial_workflow
show_preview_links: true

media_folder: "assets/img"
locale: 'de'

guide-fields: &guide-fields
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Author", name: "author", widget: "string"}
  - {label: "Icon", name: "icon", widget: "string"}
  - {label: "Url", name: "url", widget: "string"}
  - {label: "pre-intro", name: "pre-intro", widget: "string", multiple: true}

collections:
  - name: "Events Posts"
    label: "Events Posts"
    delete: false
    label_singular: "Events"
    folder: "_posts/events/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
  - name: "Team Posts"
    label: "Team Posts"
    delete: false
    label_singular: "Team"
    folder: "_posts/team/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
  - name: "Partner Posts"
    label: "Partner Posts"
    delete: false
    label_singular: "Partner"
    folder: "_posts/partner/"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.title}}"
    summary: "{{title.de}} -- {{year}}/{{month}}/{{day}}"
    fields:
      *guide-fields
